language: node_js
cache:
  directories:
  - node_modules
  - src/bower
before_script:
- bower install
- gem install scss-lint
after_script:
- if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' ]]; then ./.cf.sh clahub-staging; fi
- if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'release' ]]; then ./.cf.sh clahub; fi
